name: factory_reporting_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  crypto: ^3.0.3
  provider: ^6.0.5
  intl: ^0.18.1
  excel: ^2.0.0+1
  file_selector: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  window_manager: ^0.3.9

flutter_launcher_icons:
  # android: "launcher_icon"
  # ios: true
  # image_path: "assets/icon/icon.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo_e.png"
    icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
